<?php

use App\Person;
use App\Gender;
use App\Country;
use App\PersonRelation;
use App\RelationType;
use App\StatusPerson;
use App\MaritalStatus;
use Illuminate\Database\Seeder;

class PersonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [ 
                'name' => 'Jorge',
                'last_name' => 'Gomez',
                'rif_ci' => '18934599',
                'passport' => '18934599',
                'card_number' => '18934599',
                'expiration_date' => '2030-02-04',
                'birth_date' => '1980-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123444345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'jorge6242@gmail.com',
                'secondary_email' => 'jorge62421@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 1,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Casado',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
            [ 
                'name' => 'Johana',
                'last_name' => 'Gomez',
                'rif_ci' => '2106197',
                'passport' => '564646466',
                'card_number' => '54334567',
                'expiration_date' => '2030-02-04',
                'birth_date' => '1990-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123444345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'johana@gmail.com',
                'secondary_email' => 'johana1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 2,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Casado',
                'gender' => 'Femenino',
                'country' => 'Venezuela',
                'main_relation' => '18934599',
                'relationship' => 'CONYUGE'
            ],
            [ 
                'name' => 'Alysson',
                'last_name' => 'Gomez',
                'rif_ci' => '43556789',
                'passport' => '6757657575',
                'card_number' => '98763354',
                'expiration_date' => '2030-02-04',
                'birth_date' => '2010-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123444345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'alysson@gmail.com',
                'secondary_email' => 'alysson1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 2,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Femenino',
                'country' => 'Venezuela',
                'main_relation' => '18934599',
                'relationship' => 'HIJO/HIJA'
            ],
            [ 
                'name' => 'Tobias',
                'last_name' => 'Gomez',
                'rif_ci' => '56089897',
                'passport' => '56464566',
                'card_number' => '55678764',
                'expiration_date' => '2030-02-04',
                'birth_date' => '2015-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123444345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'tgomez@gmail.com',
                'secondary_email' => 'tgomez1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 2,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '18934599',
                'relationship' => 'HIJO/HIJA'
            ],
            [ 
                'name' => 'Luis',
                'last_name' => 'Gonzalez',
                'rif_ci' => '659887756',
                'passport' => '6465465464',
                'card_number' => 'N/A',
                'expiration_date' => null,
                'birth_date' => '1980-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => 'N/A',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => 'N/A',
                'primary_email' => 'lgonzalez@gmail.com',
                'secondary_email' => 'N/A',
                'fax' => 'N/A',
                'city' => 'N/A',
                'state' => 'N/Aa',
                'postal_code' => 'N/A',
                'isPartner' => 3,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
            [ 
                'name' => 'Ernesto',
                'last_name' => 'Villas',
                'rif_ci' => '21106197',
                'passport' => '6465464645',
                'card_number' => 'N/A',
                'expiration_date' => null,
                'birth_date' => '1980-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123553345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'evillas@gmail.com',
                'secondary_email' => 'evillas1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 1,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
            [ 
                'name' => 'Miguel',
                'last_name' => 'Perez',
                'rif_ci' => '6138049',
                'passport' => '56545435',
                'card_number' => '456666556',
                'expiration_date' => null,
                'birth_date' => '1980-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123553345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'mperez@gmail.com',
                'secondary_email' => 'mperez1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 1,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
            [ 
                'name' => 'German',
                'last_name' => 'Vera',
                'rif_ci' => '7998168',
                'passport' => '5555444566',
                'card_number' => '8878887877',
                'expiration_date' => null,
                'birth_date' => '1980-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123553345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'gvera@gmail.com',
                'secondary_email' => 'gvera@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 1,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
            [ 
                'name' => 'Oswaldo',
                'last_name' => 'Teran',
                'rif_ci' => '18934576',
                'passport' => '5555444566',
                'card_number' => '18934576',
                'expiration_date' => null,
                'birth_date' => '1980-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123553345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'oteran@gmail.com',
                'secondary_email' => 'oteran1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 1,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
            [ 
                'name' => 'Alexis',
                'last_name' => 'Sanchez',
                'rif_ci' => '7923451',
                'passport' => '111345312',
                'card_number' => '111345312',
                'expiration_date' => '2022-02-04',
                'birth_date' => '1980-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123553345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'asanchez@gmail.com',
                'secondary_email' => 'asanchez1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 2,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
            [ 
                'name' => 'Yesenia',
                'last_name' => 'Zerpa',
                'rif_ci' => '16496470',
                'passport' => '16496470',
                'card_number' => '77754534543',
                'expiration_date' => '2022-02-04',
                'birth_date' => '1985-02-04',
                'representante' => 'Representante Prueba',
                'picture' => 'partner-empty.png',
                'id_card_picture' => 'partner-empty.png',
                'address' => 'Direccion de Ejemplo',
                'telephone1' => '02392123553345',
                'telephone2' => '02392123553345',
                'phone_mobile1' => '04143444345',
                'phone_mobile2' => '04143444345',
                'primary_email' => 'yzerpa@gmail.com',
                'secondary_email' => 'yzerpa1@gmail.com',
                'fax' => '44557656757',
                'city' => 'Ciudad Prueba',
                'state' => 'Estado Prueba',
                'postal_code' => '1211',
                'isPartner' => 2,
                'type_person' => 1,
                'company_person_id' => null,
                'status' => 'Activo',
                'maritalStatus' => 'Soltero',
                'gender' => 'Masculino',
                'country' => 'Venezuela',
                'main_relation' => '',
                'relationship' => ''
            ],
        ];
        foreach ($data as $element) {
            $status = StatusPerson::where('description',$element['status'])->first();
            $maritalStatus = MaritalStatus::where('description',$element['maritalStatus'])->first();
            $gender = Gender::where('description',$element['gender'])->first();
            $country = Country::where('description',$element['country'])->first();
            $personRelation = Person::where('rif_ci', $element['main_relation'])->first();
            $person = Person::create([
                'name' => $element['name'],
                'last_name' => $element['last_name'],
                'rif_ci' => $element['rif_ci'],
                'passport' => $element['passport'],
                'card_number' => $element['card_number'],
                'expiration_date' => $element['expiration_date'],
                'birth_date' => $element['birth_date'],
                'representante' => $element['representante'],
                'picture' => $element['picture'],
                'id_card_picture' => $element['id_card_picture'],
                'address' => $element['address'],
                'telephone1' => $element['telephone1'],
                'telephone2' => $element['telephone2'],
                'phone_mobile1' => $element['phone_mobile1'],
                'phone_mobile2' => $element['phone_mobile2'],
                'primary_email' => $element['primary_email'],
                'secondary_email' => $element['secondary_email'],
                'fax' => $element['fax'],
                'city' => $element['city'],
                'state' => $element['state'],
                'postal_code' => $element['postal_code'],
                'isPartner' => $element['isPartner'],
                'type_person' => $element['type_person'],
                'company_person_id' => $element['company_person_id'],
                'status_person_id' => $status->id,
                'marital_statuses_id' => $maritalStatus->id,
                'gender_id' => $gender->id,
                'countries_id' => $country->id,
            ]);
            if($personRelation) {
                $relationType = RelationType::where('description', $element['relationship'])->first(); 
                PersonRelation::create([
                    'base_id' => $personRelation->id,
                    'related_id' => $person->id,
                    'relation_type_id' => $relationType->id,
                    'status' => 1
                ]);
            }
        }
    }
}
